name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize]
jobs:
  test:    
    runs-on: ubuntu-latest    
    steps:      
      - uses: actions/checkout@v4
      - name: test1
        env:
          GITHUB_CONTEXT: ${{ contains(toJson(github.event.commits.*.message), '#skip') }}
        run: echo "$GITHUB_CONTEXT"
      - name: test2
        env:
          COMMITS: ${{ contains(toJson(github.event.commits.*.message), '#skip') == 'false' }}
        run: echo "$COMMITS"
      - name: test3
        env:
          COMMITS1: ${{ github.event_name == 'push' && contains(toJson(github.event.commits.*.message), '#skip') == 'false'}}
        run: echo "$COMMITS1"